apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: victoria-metrics-single
      sourceRef:
        kind: HelmRepository
        name: victoria-metrics
        namespace: flux-system
  values:
    retentionPeriod: 7d

    vmagent:
      extraScrapeConfigs: |
        - job_name: "opencost"
          scrape_interval: 1m
          metrics_path: /metrics
          scheme: http
          static_configs:
            - targets:
                - opencost-exporter.opencost-exporter.svc.cluster.local:9003
