apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opencost
  namespace: opencost
spec:
  interval: 5m
  chart:
    spec:
      chart: opencost
      sourceRef:
        kind: HelmRepository
        name: opencost
        namespace: flux-system

  values:
    opencost:
      exporter:
        defaultClusterId: minikube-cluster

      prometheus:
        internal:
          enabled: true
          namespaceName: monitoring
          serviceName: prometheus-kube-prometheus-prometheus
          port: 9090

    ui:
      enabled: true
      advanced:
        enabled: true   # 👈 THIS enables Advanced UI

    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        cpu: 1
        memory: 1G
