apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: opencost
  namespace: opencost
spec:
  interval: 30m

  chart:
    spec:
      chart: opencost
      version: "1.108.x"
      sourceRef:
        kind: HelmRepository
        name: opencost
        namespace: flux-system
      interval: 12h

  install:
    remediation:
      retries: 3

  upgrade:
    remediation:
      retries: 3

  values:
    opencost:
      exporter:
        defaultClusterId: minikube

      prometheus:
        external:
          enabled: true
          url: http://vm-victoria-metrics-single-server.monitoring.svc.cluster.local:8428

    ui:
      enabled: true
      ingress:
        enabled: false

    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
