apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opencost
  namespace: opencost
spec:
  interval: 5m
  releaseName: opencost
  chart:
    spec:
      chart: opencost
      sourceRef:
        kind: HelmRepository
        name: opencost
        namespace: flux-system
  targetNamespace: opencost
  values:
    prometheus:
      external:
        enabled: true
        address: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
      internal:
        enabled: false
