apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: opencost-exporter
  namespace: flux-system
spec:
  interval: 5m
  path: ./clusters/minikube/opencost
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  validation: client

  resources:
    - namespace.yaml
    - helmrepository.yaml
    - helmrelease.yaml
